### ISSUE TITLE
numpy error on Linux

### ISSUE THREAD

**Issue by ejbman** [JuergenFleiss/aTrain#24]
I tried running my first transcription after installing on Linux Mint 21.3 Cinnamon and got:

Oh no, the system failed to transcribe 😱😱😱
Error Image
The following error occured:
`np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

Traceback:
Traceback (most recent call last): File "/home/eric/atrain_venv/lib/python3.10/site-packages/aTrain/transcribe.py", line 14, in handle_transcription for step in transcribe(prepared_file, model, language, speaker_detection, num_speakers, device, compute_type): File "/home/eric/atrain_venv/lib/python3.10/site-packages/aTrain/transcribe.py", line 34, in transcribe from .pipeline import CustomPipeline File "/home/eric/atrain_venv/lib/python3.10/site-packages/aTrain/pipeline.py", line 1, in <module> from pyannote.audio import Pipeline File "/home/eric/atrain_venv/lib/python3.10/site-packages/pyannote/audio/__init__.py", line 29, in <module> from .core.inference import Inference File "/home/eric/atrain_venv/lib/python3.10/site-packages/pyannote/audio/core/inference.py", line 49, in <module> class Inference(BaseInference): File "/home/eric/atrain_venv/lib/python3.10/site-packages/pyannote/audio/core/inference.py", line 533, in Inference missing: float = np.NaN, File "/home/eric/atrain_venv/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__ raise AttributeError(AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

**Comment by JuergenFleiss** [comment]
Could you check if the new cli works for you?

https://github.com/JuergenFleiss/atrain_core

If it works, I would ask you for a little patience, as there will soon be a new version of atrain based on it. Otherwise, we will have to work on your error in atrain_core

**Comment by JuergenFleiss** [comment]
> Could you check if the new cli works for you?
> 
> https://github.com/JuergenFleiss/atrain_core
> 
> If it works, I would ask you for a little patience, as there will soon be a new version of atrain based on it. Otherwise, we will have to work on your error in atrain_core

Please see the workaround posted in [atrain_core](https://github.com/JuergenFleiss/atrain_core/issues/10#issuecomment-2178549341) Thanks @Zahrun

pip install -U numpy==1.26.4

**Comment by ejbman** [comment]
Just a quick bid for another implementation: I'd love to be able to install via Docker container on my unRAID server, because it happens to have my best GPU. Thank you :)

**Comment by JuergenFleiss** [comment]
Solved with https://github.com/JuergenFleiss/aTrain/pull/26 thanks @samfisherirl
