### ISSUE TITLE
ctranslate2.models.Whisper( RuntimeError: CUDA failed with error initialization error   only with aTrain (not aTrain_core)

### ISSUE THREAD

**Issue by allan-simon** [JuergenFleiss/aTrain#46]
When I try to transcribe using the GPU (regardless of int8/float16) I got the following stacktrace 

```
>Traceback (most recent call last):
  File "git/open-source/atrain_venv/lib/python3.10/site-packages/aTrain/transcription.py", line 53, in try_to_transcribe
    start_transcription(settings, file_name, file_content, event_sender)
  File "git/open-source/atrain_venv/lib/python3.10/site-packages/aTrain/transcription.py", line 87, in start_transcription
    transcribe(
  File "git/open-source/atrain_venv/lib/python3.10/site-packages/aTrain_core/transcribe.py", line 273, in transcribe
    transcript = _perform_whisper_transcription(
  File "git/open-source/atrain_venv/lib/python3.10/site-packages/aTrain_core/transcribe.py", line 86, in _perform_whisper_transcription
    transcription_model = WhisperModel(model_path, device, compute_type=compute_type)
  File "git/open-source/atrain_venv/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 144, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error initialization error
```

however using aTrain_core directly  it works

searching the web I wonder if it related to 

https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing  (i.e it is  run in a fork ?)

https://github.com/SYSTRAN/faster-whisper/issues/776

**Comment by ArminHaberl** [comment]
Thanks for bringing this up! In our GUI app, we currently use `multiprocessing` to make it easier to stop transcription processes if the user decides to cancel. However, because we need to freeze the code to create an executable, we have to enable `multiprocessing.freeze_support()`, which can affect the start_method used for creating processes.

We’re aware this setup has its challenges, and we’re already planning to switch to `async` tasks instead. This change should make it easier for users to cancel transcriptions and help resolve some of the other issues we’ve run into with multiprocessing. It’s on our roadmap, and we’re aiming to roll it out in the next release.

Hope that clears things up! Let us know if you have any other questions or suggestions.
