### ISSUE TITLE
macos: cannot download Models nor transcribe with default model

### ISSUE THREAD

**Issue by dm5n** [JuergenFleiss/aTrain#54]
Hello, 

Using atrain v1.20 on macos 15.2 M4 macbook:

Error msg on attempting to download new model:

```
Show Traceback
Traceback (most recent call last): File "urllib/request.py", line
1348, in do _open File "http/client.py", line 1298, in request
File "http/client.py", line 1344, in _send_request File
"http/client.py", line 1293, in endheaders File "http/client.py",
line 1052, in _send_output File "http/client.py", line 990, in
send File "http/client.py", line 1470, in connect File "ssl.py",
line 517, in wrap_socket File "ssl.py", line 1104, in _create File
"ssl.py", line 1382, in do_handshake
ssI.SSLCertVerificationError: [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable
to get local issuer certificate (_ssl.c:1006) During handling of
the above exception, another exception occurred: Traceback
(most recent call last): File "aTrain/models.py", line 223, in
check_internet File "urllib/request.py", line 216, in urlopen File
"urllib/request.py", line 519, in open File "urllib/request.py",
line 536, in _open File "urllib/request.py", line 496, in
_call_chain File "urllib/request.py", line 1391, in https_open
File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: During handling of the above exception,
another exception occurred: Traceback (most recent call
last): File "aTrain/models.py", line 211, in
try_to_download _model File "aTrain/models.py", line 225, in
check_internet ConnectionError: We cannot reach Hugging
Face. Most likely you are not connected to the internet.
```

And error msg on attempting to transcribe using default model (large-v3-turbo) using .m4a and .mp3 versions of same audiofile that had been verified to work in VLC player:

```
Show Traceback へ
Traceback (most recent call last): File
"aTrain_core/transcribe.py", line 115, in
_prepare_metadata_creation File "faster_whisper/audio.py", line
46, in decode_audio File "av/container/core.pyx", line 420, in
av.container.core.open File "av/container/core.pyx", line 266, in
av.container.core.Container.__cinit_ File
"av/container/core.pyx", line 286, in
av.container.core.Container.err_check File "av/error.pyx", line
328, in av.error.err_check av.error.InvalidDataError: [Errno
1094995529] Invalid data found when processing input: "
During handling of the above exception, another exception
occurred: Traceback (most recent call last): File
"aTrain/transcription.py", line 52, in try_to_transcribe File
"aTrain/transcription.py", line 86, in start_transcription File
"aTrain_core/transcribe.py", line 300, in transcribe File
"aTrain_core/transcribe.py", line 118, in
_prepare_metadata_creation Exception: Attention: Your file has
no audio.
```

**Comment by andreafooo** [comment]
Hi! 

Thank you for the feedback - regarding the second error message: Does your filename have white space? If so, a quick fix would be to remove the whitespaces in the file name (e.g. exchange them with underscores). We have added a note regarding this behaviour in v1.2.1. I hope this helps :)

**Comment by dm5n** [comment]
Thanks. I amended the filename to replace spaces with _. 

But still error:

Show Traceback
Traceback (most recent call last): File
"aTrain_core/transcribe.py", line 115, in
_prepare_metadata_creation File "faster_whisper/audio.py", line
46, in decode_audio File "av/container/core.pyx", line 420, in
av.container.core.open File "av/container/core.pyx", line 266, in
av.container.core.Container.__cinit__ File
"av/container/core.pyx", line 286, in
av.container.core.Container.err_check File "av/error.pyx", line
328, in av.error.err_check av.error.InvalidDataError: [Errno
1094995529] Invalid data found when processing input:"
During handling of the above exception, another exception
occurred: Traceback (most recent call last): File
"aTrain/transcription.py", line 52, in try_to_transcribe File
"aTrain/transcription.py", line 86, in start_transcription File
"aTrain_core/transcribe.py", line 300, in transcribe File
"aTrain_core/transcribe.py", line 118, in
_prepare_metadata_creation Exception: Attention: Your file has
no audio.

**Comment by JuergenFleiss** [comment]
Hi,

@dm5n, @andreafooo  built a signed new mac version. 

You can find it temporarily here: https://cloud.uni-graz.at/s/qQZS6mM3bkCrB6W

We will also publish it on our website next week 
https://business-analytics.uni-graz.at/de/forschung/atrain/download/

**Comment by JuergenFleiss** [comment]
Hi, please test the newest mac version 
https://business-analytics.uni-graz.at/de/forschung/atrain/download/

**Comment by JuergenFleiss** [comment]
Hi everyone, mac os 1.2.4 is now online and can be downloaded here
https://bandas.uni-graz.at/downloads/aTrain_v1.2.4.dmg

Can you let me know if the error is still present with the version signed by apple?

**Comment by tophee** [comment]
I am using v1.2.4 on macOS (MBP, M4) and I am getting this error when trying to downoload a model:

![Image](https://github.com/user-attachments/assets/6af0ed09-c3a9-4b26-a388-2ef7bdcabbc9)

**Comment by JuergenFleiss** [comment]
@tophee While this seems to be an ssl certification error,  can you also check if your firewall is blocking anything and that you are connected to the internet?

**Comment by tophee** [comment]
I don't think I'm using a firewall and of course I'm connected to the internet. 

Since this error seems to happen in python, I could start trouble shooting by entering some command on the python command line. What would be a suitable command to try? Or is aTrain brining its own python instance? (In which case it wouldn't help if I tested via my default python environment.)

**Comment by austrosaraceno** [comment]
Hi, I also have the same problem. When I try to download another model version, the same error message appears! I am using the latest available version of strain (1.2.4). Has anyone figured it out?

p.s.
I use atrain with no problem on windows

**Comment by JuergenFleiss** [comment]
@ecomuse-se posted a workaround for when the model download fails under macos in https://github.com/JuergenFleiss/aTrain/issues/107

I will close this issue as a duplicate of the more up to date https://github.com/JuergenFleiss/aTrain/issues/107
